blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.anasayfa, name='index'),
    url(r'^arama/$', views.results, name='search'),
    url(r'^anasayfa/sayfa/(?P<page_number>[0-9]+)/$', views.anasayfa, name='page'),
    url(r'^anasayfa/$', views.anasayfa, name='anasayfa'),
    url(r'^kategori/(?P<category_slug>[0-9A-Za-z\-]+)/$', views.category, name='category'),
    url(r'^etiket/(?P<tag_slug>[0-9A-Za-z\-]+)/$', views.tag, name='tag'),
    url(r'^(?P<article_slug>[0-9A-Za-z\-]+)/$', views.article, name='article'),
    url(r'yeni-yorum/(?P<article_slug>[0-9A-Za-z\-]+)/$', views.add_comment, name='new_comment'),
    url(r'yeni-yorum/(?P<article_slug>[0-9A-Za-z\-]+)/(?P<comment_id>[0-9A-Za-z\-]+)/$',
        views.add_comment, name='new_reply')
]

mertakdeniz/urls.py
from django.conf.urls import url
from . import views

mrt_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^cPanel/', admin.site.urls),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^', include('blog.urls')),  # anasayfa!


]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Kategori")
    slug = models.CharField(max_length=150, unique=True, verbose_name="Slug")
    created_at = models.DateTimeField(blank=True, null=True, auto_now_add=True, verbose_name="Oluşturulma")
    updated_at = models.DateTimeField(blank=True, null=True, auto_now=True, verbose_name="Düzenlenme")
    parent = models.ForeignKey('self', null=True, blank=True)

    class Meta:
        verbose_name = "Kategori"
        verbose_name_plural = "Kategoriler"
        ordering = ['name']

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name="Etiket")
    slug = models.CharField(max_length=100, verbose_name="Slug", null=True, blank=True)

    class Meta:
        verbose_name = "Etiket"
        verbose_name_plural = "Etiketler"

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=150, unique=True, verbose_name="Başlık")
    slug = models.CharField(max_length=150, verbose_name="Slug", unique=True)
    description = models.TextField(verbose_name="Açıklama", null=True, blank=True)
    content = models.TextField(verbose_name="İçerik")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Kategori")
    tags = models.ManyToManyField(Tag, blank=True)
    created_at = models.DateTimeField(blank=True, null=True, auto_now_add=True, verbose_name="Oluşturulma")
    updated_at = models.DateTimeField(blank=True, null=True, auto_now=True, verbose_name="Düzenlenme")

    class Meta:
        verbose_name = "Makale"
        verbose_name_plural = "Makaleler"
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_active_comment_count(self):
        return self.comment_set.filter(status__exact=True).count()


class Comment(models.Model):
    owner_name = models.CharField(max_length=150, verbose_name="Ad-Soyad")
    email = models.CharField(max_length=150, verbose_name="E-Posta")
    text = models.TextField(verbose_name="Yorum")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Makale")
    parent = models.ForeignKey('self', null=True, blank=True)
    status = models.BooleanField(default=0, verbose_name="Durum")
    created_at = models.DateTimeField(blank=True, null=True, auto_now_add=True, verbose_name="Oluşturulma")
    updated_at = models.DateTimeField(blank=True, null=True, auto_now=True, verbose_name="Düzenlenme")

    class Meta:
        verbose_name = "Yorum"
        verbose_name_plural = "Yorumlar"
        ordering = ['-created_at']

    def __str__(self):
        return "%s - %s" % (self.owner_name, self.created_at)

mertakdeniz/models.py
from django.db import models


class Config(models.Model):
    site_name = models.CharField(max_length=150)
    site_version = models.FloatField()

    def __str__(self):
        return self.site_name


class Global(models.Model):
    facebook = models.CharField(max_length=150)
    twitter = models.CharField(max_length=150)

    def __str__(self):
        return self.facebook

# Create your models here.

blog/views.py
from blog.models import Category, Article, Tag, Comment
from django.shortcuts import get_object_or_404, render, get_list_or_404, redirect
from django.db.models import Q


def index(request):
    return render(request, 'blog/rest.html')


def anasayfa(request):
    return render(request, 'blog/home.html', {
        'page_title': 'Anasayfa',
        'articles': Article.objects.all()
    })


def article(request, article_slug):
    return render(request, 'blog/detail.html', {
        'article': get_object_or_404(Article, slug=article_slug),
        'article_comments': Comment.objects
                  .filter(article__slug__exact=article_slug)
                  .filter(parent__isnull=True)
                  .filter(status__exact=True)})


def category(request, category_slug):
    current_category = get_object_or_404(Category, slug=category_slug)
    return render(request, 'blog/home.html', {
        'page_title': current_category.name,
        'articles': Article.objects.filter(category__slug__exact=category_slug),
        'current_category': current_category
    })


def tag(request, tag_slug):
    current_tag = get_object_or_404(Tag, slug=tag_slug)
    return render(request, 'blog/home.html', {
        'page_title': current_tag.name,
        'articles': Article.objects.filter(tags__slug__exact=tag_slug),
        'current_tag': current_tag
    })


def results(request):
    if request.method == "POST":
        keyword = request.POST['keyword']
        result = Article.objects.filter(Q(title__icontains=keyword) |
                                        Q(content__icontains=keyword) |
                                        Q(description__icontains=keyword) |
                                        Q(tags__name__icontains=keyword)).distinct()
        return render(request, 'blog/home.html', {
            'page_title': "%s için sonuçlar" % keyword,
            'articles': result
        })
    else:
        return render(request, 'blog/home.html', {
            'page_title': 'anasayfa',
            'articles': Article.objects.all()
        })


def add_comment(request, article_slug, comment_id=None):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']

        current_article = get_object_or_404(Article, slug=article_slug)

        if comment_id is not None:
            current_comment = get_object_or_404(Comment, id=comment_id)
            new_comment = Comment(owner_name=name,
                                  email=email,
                                  text=message,
                                  article=current_article,
                                  parent=current_comment)
        else:
            new_comment = Comment(owner_name=name,
                                  email=email,
                                  text=message,
                                  article=current_article)

        new_comment.save()

        return redirect('article', article_slug=article_slug, permanent=True)

mertakdeniz/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader


def index(request):
    template = loader.get_template('mertakdeniz/index.html')
    context = RequestContext(request, {})
    return HttpResponse(template.render(context))
# Create your views here.

blog/templates/blog/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Mert Özgür Akdeniz kişisel blog">
    <meta name="author" content="Mert Özgür Akdeniz">
    <title>Yapım Aşamasında | {{ settings.site_name }}</title>
    {% load staticfiles %}
    <link href="{% static "blog/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "blog/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "blog/css/main.css" %}" rel="stylesheet">
    <link href="{% static "blog/css/responsive.css" %}" rel="stylesheet">
    <link href="{% static "blog/css/style.css" %}" rel="stylesheet">

    <!--[if lt IE 9]>
        <script src="{% static "blog/js/html5shiv.js" %}"></script>
        <script src="{% static "blog/js/respond.min.js" %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static "blog/images/ico/favicon.ico" %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "blog/images/ico/apple-touch-icon-144-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "blog/images/ico/apple-touch-icon-114-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "blog/images/ico/apple-touch-icon-72-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" href="{% static "blog/images/ico/apple-touch-icon-57-precomposed.png" %}">
</head><!--/head-->

<body>
    <div class="logo-image">
       <a href="{% url 'index' %}"><img class="img-responsive" src="{% static "blog/images/logo2.png" %}" alt=""> </a>
    </div>
     <section id="coming-soon">
         <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <div class="text-center coming-content">
                        <h1>Yapım Aşamasında</h1>
                        <h1>{{ sayi }}</h1>
                        <p>Sistem mimarisini ve tasarımı yeniliyorum. Yakında, hiç olmadığı kadar hızlı bir sistem ve tasarım ile
                        burada olacağım.</p>
                        <div class="social-link">
                            <span><a href="https://facebook.com/themrtakdeniz"><i class="fa fa-facebook"></i></a></span>
                            <span><a href="https://twitter.com/mrtoakdeniz"><i class="fa fa-twitter"></i></a></span>
                            <span><a href="https://plus.google.com/+Mert%C3%96zg%C3%BCrAkdeniz/posts"><i class="fa fa-google-plus"></i></a></span>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="time-count">
                        <ul id="countdown">
                            <li class="angle-one">
                                <span class="days time-font">00</span>
                                <p>Gün</p>
                            </li>
                            <li class="angle-two">
                                <span class="hours time-font">00</span>
                                <p>Saat</p>
                            </li>
                            <li class="angle-three">
                                <span class="minutes time-font">00</span>
                                <p class="minute">Dakika</p>
                            </li>
                            <li class="angle-four">
                                <span class="seconds time-font">00</span>
                                <p>Saniye</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="coming-soon-footer" class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center">
                    {% now "Y" as current_year %}
                    <p>&copy; Mert Özgür Akdeniz {{ current_year }}. Her hakkı saklıdır.</p>
                    <p>Tasarım: <a target="_blank" href="http://www.themeum.com">Themeum</a></p>
                </div>
            </div>
        </div>
    </section>


    <script type="text/javascript" src="{% static "blog/js/jquery-2.1.4.min.js" %}"></script>
    <script type="text/javascript" src="{% static "blog/js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "blog/js/coundown-timer.js" %}"></script>
    <script type="text/javascript" src="{% static "blog/js/wow.min.js" %}"></script>
    <script type="text/javascript" src="{% static "blog/js/main.js" %}"></script>
    <script type="text/javascript">
            //Countdown js
         $("#countdown").countdown({
                date: "20 december 2015 12:00:00",
                format: "on"
            },
            function() {
                // callback function
        });
    </script>

</body>
</html>

blog/templates/blog/home.html
{% extends "blog/layout.html" %}
{% load staticfiles %}
{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <section id="blog">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-7">
                    <div class="row">
                        <div class="col-sm-12 col-md-12">
                            {% if not articles %}
                                <h2>Burada görüntülenecek bir şey yok!</h2>
                            {% endif %}
                        </div>
                        {% for article in articles  %}
                            <div class="col-sm-12 col-md-12">
                                <div class="single-blog single-column">
                                    {% comment "Buraya da resim gelecek! %}
                                    <div class="post-thumb">
                                        <a href="{{ article.title }}"><img src="{% static "blog/images/blog/7.jpg" %}" class="img-responsive" alt=""></a>
                                        <div class="post-overlay">
                                           <span class="uppercase"><a href="#">{{ article.created_at|date:'d' }} <br><small>{{ article.created_at|date:'M' }}</small></a></span>
                                       </div>
                                    </div>
                                    {% endcomment %}
                                    <div class="post-content overflow">
                                        <h2 class="post-title bold">
                                            <a href="{% url 'article' article.slug %}">{{ article.title|title }}</a>
                                        </h2>
                                        {% autoescape off %}
                                            <p>{{ article.description }}</p>
                                        {% endautoescape %}
                                        <a href="{% url 'article' article.slug %}" class="read-more">Devamını oku...</a>
                                        <div class="post-bottom overflow">
                                            <ul class="nav navbar-nav post-nav">
                                                <li>
                                                    <span>
                                                        <i class="fa fa-tag"></i>
                                                        {% spaceless %}{% for tag in article.tags.all %}<a href="{% url 'tag' tag.slug %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
                                                        {% endfor %}{% endspaceless %}
                                                    </span>
                                                </li>
                                                <li><i class="fa fa-comments"></i> {{ article.get_active_comment_count }} Yorum</li>
                                                <li><i class="fa fa-comments"></i> {{ article.created_at }}</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% comment "pagination will be here!" %}
                    <div class="blog-pagination">
                        <ul class="pagination">
                            {% if articles.has_previous %}
                                <li><a href="{% url 'page' articles.previous_page_number %}">left</a></li>
                            {% endif %}

                            <li class="active">
                                <a href="#">{{ articles.number }}</a> of {{ articles.paginator.num_pages }}
                            </li>

                            {% if articles.has_next %}
                                <li><a href="{% url 'page' articles.next_page_number %}">right</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    {% endcomment %}
                 </div>
                {% include "blog/sidebar_right.html" %}
            </div>
        </div>
    </section>
    <!--/#blog-->
{% endblock %}

blog/templates/blog/rest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Mert Özgür Akdeniz kişisel blog">
    <meta name="author" content="Mert Özgür Akdeniz">
    <title>Yapım Aşamasında | {{ settings.site_name }}</title>
    {% load staticfiles %}
    <link href="{% static "blog/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "blog/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "blog/css/main.css" %}" rel="stylesheet">
    <link href="{% static "blog/css/responsive.css" %}" rel="stylesheet">

    <!--[if lt IE 9]>
        <script src="{% static "blog/js/html5shiv.js" %}"></script>
        <script src="{% static "blog/js/respond.min.js" %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static "blog/images/ico/favicon.ico" %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "blog/images/ico/apple-touch-icon-144-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "blog/images/ico/apple-touch-icon-114-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "blog/images/ico/apple-touch-icon-72-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" href="{% static "blog/images/ico/apple-touch-icon-57-precomposed.png" %}">
</head><!--/head-->

<body>
    <div class="logo-image">
       <a href="{% url 'index' %}"><img class="img-responsive" src="{% static "blog/images/logo2.png" %}" alt=""> </a>
    </div>
     <section id="coming-soon">
         <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <div class="text-center coming-content">
                        <h1>Yapım Aşamasında</h1>
                        <p>Sistem mimarisini ve tasarımı yeniliyorum. Yakında, hiç olmadığı kadar hızlı bir sistem ve tasarım ile
                        burada olacağım.</p>
                        <div class="social-link">
                            <span><a href="https://facebook.com/themrtakdeniz"><i class="fa fa-facebook"></i></a></span>
                            <span><a href="https://twitter.com/mrtoakdeniz"><i class="fa fa-twitter"></i></a></span>
                            <span><a href="https://plus.google.com/+Mert%C3%96zg%C3%BCrAkdeniz/posts"><i class="fa fa-google-plus"></i></a></span>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="time-count">
                        <ul id="countdown">
                            <li class="angle-one">
                                <span class="days time-font">00</span>
                                <p>Gün</p>
                            </li>
                            <li class="angle-two">
                                <span class="hours time-font">00</span>
                                <p>Saat</p>
                            </li>
                            <li class="angle-three">
                                <span class="minutes time-font">00</span>
                                <p class="minute">Dakika</p>
                            </li>
                            <li class="angle-four">
                                <span class="seconds time-font">00</span>
                                <p>Saniye</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="coming-soon-footer" class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center">
                    {% now "Y" as current_year %}
                    <p>&copy; Mert Özgür Akdeniz {{ current_year }}. Her hakkı saklıdır.</p>
                    <p>Tasarım: <a target="_blank" href="http://www.themeum.com">Themeum</a></p>
                </div>
            </div>
        </div>
    </section>


    <script type="text/javascript" src="{% static "blog/js/jquery-2.1.4.min.js" %}"></script>
    <script type="text/javascript" src="{% static "blog/js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "blog/js/coundown-timer.js" %}"></script>
    <script type="text/javascript" src="{% static "blog/js/wow.min.js" %}"></script>
    <script type="text/javascript" src="{% static "blog/js/main.js" %}"></script>
    <script type="text/javascript">
            //Countdown js
         $("#countdown").countdown({
                date: "20 december 2015 12:00:00",
                format: "on"
            },
            function() {
                // callback function
        });
    </script>

</body>
</html>

blog/templates/blog/sidebar_right.html
<div class="col-md-3 col-sm-5">
    <div class="sidebar blog-sidebar">
        <div class="sidebar-item categories">
            <h3>Kategoriler</h3>
            <ul class="nav navbar-stacked">
                {% for category in categories %}
                    {% if category.id == article.category.id or current_category.id == category.id %}
                    <li class="active">
                    {% else %}
                    <li>
                    {% endif %}
                        <a href="{% url 'category' category.slug %}">{{ category.name }}
                            <span class="pull-right">({{ category.article_set.count }})</span>
                        </a>
                    </li>
                    {% for sub_category in category.category_set.all %}
                        {% if sub_category.id == article.category.id or current_category.id == sub_category.id %}
                        <li class="sub-category active">
                        {% else %}
                        <li class="sub-category">
                        {% endif %}
                            <a href="{% url 'category' sub_category.slug %}"><span>{{ sub_category.name }}</span>
                                <span class="pull-right">({{ sub_category.article_set.count }})</span>
                            </a>
                        </li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
        <div class="sidebar-item tag-cloud">
            <h3>Etiket Bulutu</h3>
            <ul class="nav nav-pills">
                {% for tag in tags %}
                    <li><a href="{% url 'tag' tag.slug %}">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

blog/templates/blog/tag_pool.html
{% extends "blog/layout.html" %}
{% block content %}
    {% for article in articles %}
    {{ article.title }}
{% endfor %}
asdfasdf
{% endblock %}

blog/templates/blog/test.html
{% extends "blog/layout.html" %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <section id="blog">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-7">
                    <div class="row">
                        {% for article in articles  %}
                            <div class="col-sm-12 col-md-12">
                                <div class="single-blog single-column">
                                    <div class="post-thumb">
                                        <a href="{{ article.title }}"><img src="images/blog/7.jpg" class="img-responsive" alt=""></a>
                                        <div class="post-overlay">
                                           <span class="uppercase"><a href="#">14 <br><small>Feb</small></a></span>
                                       </div>
                                    </div>
                                    <div class="post-content overflow">
                                        <h2 class="post-title bold"><a href="{% url 'article' article.slug %}">{{ article.title|title }}</a></h2>
                                        <h3 class="post-author"><a href="#">Posted by micron News on {{ article.created_at }}</a></h3>
                                        <p>{{ article.content|truncatewords_html:30 }}</p>
                                        <a href="{% url 'article' article.slug %}" class="read-more">Devamını oku...</a>
                                        <div class="post-bottom overflow">
                                            <ul class="nav navbar-nav post-nav">
                                                <li><a href="#"><i class="fa fa-tag"></i>Creative</a></li>
                                                <li><a href="#"><i class="fa fa-heart"></i>32 Love</a></li>
                                                <li><a href="#"><i class="fa fa-comments"></i>3 Comments</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="blog-pagination">
                        <ul class="pagination">
                          <li><a href="#">left</a></li>
                          <li><a href="#">1</a></li>
                          <li><a href="#">2</a></li>
                          <li class="active"><a href="#">3</a></li>
                          <li><a href="#">4</a></li>
                          <li><a href="#">5</a></li>
                          <li><a href="#">6</a></li>
                          <li><a href="#">7</a></li>
                          <li><a href="#">8</a></li>
                          <li><a href="#">9</a></li>
                          <li><a href="#">right</a></li>
                        </ul>
                    </div>
                 </div>
                <div class="col-md-3 col-sm-5">
                    <div class="sidebar blog-sidebar">
                        <div class="sidebar-item categories">
                            <h3>Kategoriler</h3>
                            <ul class="nav navbar-stacked">
                                {% for category in categories %}
                                    <li>
                                        <a href="{% url 'category' category.slug %}">{{ category.name }}
                                            <span class="pull-right">({{ category.article_set.count }})</span>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="sidebar-item tag-cloud">
                            <h3>Tag Cloud</h3>
                            <ul class="nav nav-pills">
                                <li><a href="#">Corporate</a></li>
                                <li><a href="#">Joomla</a></li>
                                <li><a href="#">Abstract</a></li>
                                <li><a href="#">Creative</a></li>
                                <li><a href="#">Business</a></li>
                                <li><a href="#">Product</a></li>
                            </ul>
                        </div>
                        <div class="sidebar-item popular">
                            <h3>Latest Photos</h3>
                            <ul class="gallery">
                                <li><a href="#"><img src="images/portfolio/popular1.jpg" alt=""></a></li>
                                <li><a href="#"><img src="images/portfolio/popular2.jpg" alt=""></a></li>
                                <li><a href="#"><img src="images/portfolio/popular3.jpg" alt=""></a></li>
                                <li><a href="#"><img src="images/portfolio/popular4.jpg" alt=""></a></li>
                                <li><a href="#"><img src="images/portfolio/popular5.jpg" alt=""></a></li>
                                <li><a href="#"><img src="images/portfolio/popular1.jpg" alt=""></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/#blog-->
{% endblock %}